In [1]:
import tensorflow as tf
import numpy as np

# Some of the Tensors Type in TensorFlow

1.   Constant Tensor
2.   Variable Tensor
3.   Ragged Tensor
4.   Sparse Tensor




# 1. Constant Tensor

In [ ]:
constant = tf.constant([1.0,2.0,3.0])
print(constant)
# Numpy array can also be passed as an input to tf.constant
#shape and dtype is inferred from the input given if not given
array = np.ones((2,2))
constant_array = tf.constant(array)
print(constant_array)
#we can also further define shape parameter to reshape the constant tensor
constant_reshaped = tf.constant(array,shape=(1,4))
print(constant_reshaped)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float64)
tf.Tensor([[1. 1. 1. 1.]], shape=(1, 4), dtype=float64)


In [ ]:
#Constant tensor cannot be modified. we will get error while trying to do so
try:
  constant.assign([4.0,5.0,6.0])
except AttributeError as e:
  print(e)

'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


In [ ]:
# Constant tensor can be exported to numpy as well
constant_to_numpy = constant.numpy()
constant_to_numpy

array([1., 2., 3.], dtype=float32)

# 2. Variable Tensor

In [ ]:
variable = tf.Variable([2,4,6])
print(variable)
var_arr = np.ones((2,2))
variable_array = tf.Variable(var_arr)
print(variable_array)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 4, 6], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float64, numpy=
array([[1., 1.],
       [1., 1.]])>


In [ ]:
train_var = tf.Variable(2.0,trainable=True)
no_train_var = tf.Variable(3.0,trainable=False)
# GradientTape is the tensorflow API used to calcilate gradient w.r.t variable during model training
# Will understand this API in more detail in later videos
with tf.GradientTape(persistent = True) as tape:
  # Defining chain of equation w.r.t variables defined
  z1 = train_var * no_train_var
  z2 = z1**2
# Since no_train_var trainable parameter is set to False,
# tensorflow will not watch this variable life-cycle and hence will not give gradient
print(tape.gradient(z2,no_train_var))
# expected answer dz2/dtrain_var = 2*z1*no_train_var = 2.0*(2.0*3.0)*3.0 = 36.0 -> Simple differentiation
print(tape.gradient(z2,train_var))

None
tf.Tensor(36.0, shape=(), dtype=float32)


In [5]:
default_name = tf.Variable([2.0])
print(default_name)
#Giving a unique name to variable
variable_name = tf.Variable([5.0,6.0,7.0],name='variable_new_name')
print(variable_name)
# Explicit dtype
variable_dtype = tf.Variable([2,3,4],dtype=tf.float64)
print(variable_dtype)

# We should not give incompatible shape parameter while creating variable
try:
  var_incompatible_shape = tf.Variable([2,3,4],shape=(2,3))
except ValueError as e:
  print(e)

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.], dtype=float32)>
<tf.Variable 'variable_new_name:0' shape=(3,) dtype=float32, numpy=array([5., 6., 7.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float64, numpy=array([2., 3., 4.])>
In this `tf.Variable` creation, the initial value's shape ((3,)) is not compatible with the explicitly supplied `shape` argument ((2, 3)).


In [ ]:
var = tf.Variable([[1,2],[3,4]])
print(var)
print(var.shape)
print(var.dtype)
print(var.numpy())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
(2, 2)
<dtype: 'int32'>
[[1 2]
 [3 4]]


In [ ]:
var1 = tf.Variable([3,4,5])
var2 = tf.Variable(var1)
var1.assign([9,1,2])
print(var1)
print(var2)
# We cannot assign value of different shape and type
try:
  var1.assign([1,2,3,4])
except ValueError as e:
  print(e)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([9, 1, 2], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([3, 4, 5], dtype=int32)>
Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (3,), and the assigned value shape (4,) are incompatible.


In [ ]:
try:
  var1.assign([1.0,2.0,3.0])
except TypeError as e:
  print(e)

Cannot convert [1.0, 2.0, 3.0] to EagerTensor of dtype int32


In [ ]:
var2 = tf.Variable([4.0,5.0,1.0])
var2.assign_add([4.0,1.0,2.0])
print(var2)
var2.assign_sub([7.0,9.0,6.0])
print(var2)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([8., 6., 3.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 1., -3., -3.], dtype=float32)>


# 3. Ragged Tensor

In [ ]:
non_rect_arr = [ [1.0,2.0,3.0],
                 [5.0,7.0],
                 [9.0]
                ]
try:
  non_rect_const = tf.constant(non_rect_arr)
except ValueError as e:
  print(e)
ragged_tensor = tf.ragged.constant(non_rect_arr)
print(ragged_tensor)
print(ragged_tensor.shape)

Can't convert non-rectangular Python sequence to Tensor.
<tf.RaggedTensor [[1.0, 2.0, 3.0], [5.0, 7.0], [9.0]]>
(3, None)


In [ ]:
ragged1 = tf.RaggedTensor.from_value_rowids(
    values=[3, 1, 4, 1, 5, 9, 2],
    value_rowids=[0, 0, 0, 0, 2, 2, 3])
print(ragged1)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9], [2]]>


In [ ]:
ragged2 = tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2],
    row_lengths=[4, 0, 2, 1]
    )
print(ragged2)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9], [2]]>


# 4. Sparse Tensor

In [ ]:
'''
Consider below example where most of the entries is 0. If we can store only
non-zero values and its coordiante it will be more efficient than storing
complete tensor. tf.sparse.SparseTesnor is used to store exactly these kind
of sparse tensor.

[[1,0,0,0],
  [0,2,0,0],
  [0,0,0,0],
  [0,0,0,0]]

'''
sparse_tensor = tf.sparse.SparseTensor(indices = [[0,0],[1,1]],values = [1,2],dense_shape = [4,4])
print(sparse_tensor)
# We can convert sparse tensor to dense tensor
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(4, 4), dtype=int32)


Indexing the Tensor

In [ ]:
# Single axis Tensor
single_axis_Tensor = tf.constant([1,2,3,4,5,6,7,8,9])
print(single_axis_Tensor)
# Axis will be gone
print(single_axis_Tensor[3])
# We will keep axis using :
print(single_axis_Tensor[2:3])
# Select from begining to end but take every second element
print(single_axis_Tensor[0:11:2])
# print in reverse order using negative index
print(single_axis_Tensor[::-1])

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor([9 8 7 6 5 4 3 2 1], shape=(9,), dtype=int32)


In [ ]:
# Multi Axis Tensor
multi_axis_tensor1 = tf.constant([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ])
print(multi_axis_tensor1)
print(multi_axis_tensor1[:-1,0:2])

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 2]
 [5 6]], shape=(2, 2), dtype=int32)


In [ ]:
multi_axis_tensor2 = tf.constant([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]],
    [[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24]]
    ])
print(multi_axis_tensor2)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(multi_axis_tensor2[:,:,0])

tf.Tensor(
[[ 1  4]
 [ 7 10]
 [13 16]
 [19 22]], shape=(4, 2), dtype=int32)


Reshaping Tensors

In [ ]:
constant_tensor = tf.constant([1,2,3,4,5,6,7,8,9,0])
print(constant_tensor)
print(tf.reshape(constant_tensor,[5,2]))

tf.Tensor([1 2 3 4 5 6 7 8 9 0], shape=(10,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]], shape=(5, 2), dtype=int32)


In [ ]:
#flatten the tensor
constant_tesnor_1 = tf.constant([[1,2,3],[4,5,6]])
print(constant_tesnor_1)
print(tf.reshape(constant_tesnor_1,[-1]))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
#combining adjacent axis
print(multi_axis_tensor2)
print(tf.reshape(multi_axis_tensor2,[4*2,-1]))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]], shape=(8, 3), dtype=int32)
